apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: choreoSvc1
  projectName: choreoProject1
  annotations:
    componentType: service
spec:
  inbound:
    - name: choreoSvc1
      port: 3000
      type: REST
      context: .
      schemaFilePath: openapi.yaml
